# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache:
  bundler: true
osx_image: xcode11.6

script:
- bundle exec fastlane test
- pod lib lint --quick
