name: PR

on:
  pull_request: 
    branches:
      - develop

jobs:
  pr:
    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Prepare
        run: bundle install
      
      - name: Test
        run: bundle exec fastlane test